### ISSUE TITLE
AngularJS compatibility 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-signature/GroupDocs.Signature-for-.NET-MVC#28]
This issue is raised in https://forum.groupdocs.com/t/angularjs-support/7737/6
Hi, Let me share user's concern:

_Looking at the source code this is an angular 2+ sample, not an angular JS (older versions of angular that is not compatible with the newer version).
Do you by any chance have a sample of the your signature element. A fallback could be a jQuery example._

Do we have discontinued jQuery support? 
Please assist. Thanks

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

Yes, we have discontinued jQuery support, however you can checkout following commit [b965c8d14c](https://github.com/groupdocs-signature/GroupDocs.Signature-for-.NET-MVC/tree/b965c8d14c9df73a23b734794281e800272aa3c8) which uses our latest jQuery example.

**Please note** that since we have discontinued jQuery support, all issues related to jQuery **won't** be fixed, instead please use Angular version (latest master commit).

Thanks.
